FROM python:3.9

WORKDIR /app

RUN pip install poetry==1.8.5

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

COPY . /app

EXPOSE 50001

CMD ["poetry", "run", "python", "./app.py"]