BASE_DATA_PATH = "./data"


# Keywords related to Disaster & Emergency Management
DEM_KEYWORDS = [
    "disaster management",
    "natural disasters",
    "human-made disasters",
    "emergency planning",
    "crisis response",
    "disaster risk reduction",
    "disaster-prone areas",
    "emergency preparedness",
    "public health emergencies",
    "search and rescue operations",
    "disaster mitigation",
    "volcanic eruptions",
    "tsunamis",
    "disaster prediction",
    "emergency warning systems",
    "hurricanes",
    "typhoons",
    "emergency evacuation",
    "emergency medical services",
    "disaster zones",
    "post-disaster assessments",
    "disaster recovery",
    "disaster relief operations",
    "chemical spills",
    "nuclear accidents",
    "disaster mapping",
    "emergency monitoring",
    "disaster satellite imagery",
    "wildfire",
    "structural collapses",
    "crisis communication",
    "cyber-attack",
    "disease outbreak",
    "pandemics",
    "bioterrorism",
    "crowd disaster",
    "disaster resilience",
    "emergency responses",
    "climate change",
    "drought",
    "support post-disasters",
    "emergency operation centers",
    "rapid decision-making in emergencies",
    "emergency risk assessment",
    "industrial accidents",
    "first responder effectiveness",
    "tornadoes",
    "landslide",
    "disaster impact analysis",
    "disaster contingency planning",
    "emergency management",
    "hazard mitigation",
    "hurricane",
    "earthquake",
    "floods",
    "natural hazards"
]

# Keywords related to Health,Safety & Environment (HSE)
HSE_KEYWORDS = [
    "Health, Safety and Environment",
    "workplace safety",
    "environmental protection",
    "HSE risk management",
    "HSE tools",
    "health and safety",
    "industrial safety",
    "occupational health in HSE",
    "workplace disease prevention",
    "workplace wellness",
    "mental health in workplaces",
    "industrial hygiene monitoring",
    "ergonomics in workplaces",
    "public health risk management",
    "fatigue detection in workplaces",
    "hazard identification in workplaces",
    "hazard mitigation strategies",
    "accident prevention in workplaces",
    "workplace safety audits",
    "personal protective equipment (PPE)",
    "incident monitoring and reporting",
    "safety management systems",
    "human error in safety operations",
    "fire and explosion risk assessment",
    "chemical spill response",
    "pollution monitoring and control",
    "waste management practices",
    "renewable energy and HSE",
    "water conservation strategies",
    "carbon footprint reduction techniques",
    "biodiversity and environmental protection",
    "climate change and sustainability",
    "environmental compliance standards",
    "construction site safety",
    "HSE in oil and gas",
    "manufacturing safety protocols",
    "mining safety procedures",
    "healthcare safety guidelines",
    "agriculture HSE practices",
    "transportation safety measures",
    "chemical industry safety management",
    "predictive maintenance in safety",
    "geospatial analysis for HSE",
    "environmental impact assessments",
    "disaster preparedness and management",
    "air quality monitoring",
    "emergency evacuation planning",
    "ISO 45001 compliance",
    "ISO 14001 environmental management",
    "sustainable safety practices",
    "smart HSE technologies",
]
